### ISSUE TITLE
Can not install.

### ISSUE THREAD

**Issue by teo0781** [Senither/ShareX-Media-Server#19]
This may be a problem on my end, but i can not install, it fails on the "php artasian migrate" step.
I am using HeidiSQL, version: **mysql  Ver 15.1 Distrib 10.5.10-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2**

Error:
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: select * from information_schema.tables where table_schema = media and table_name = migrations and table_type = 'BASE TABLE')

Am i doing something wrong?
Apologies if i am doing something wrong by the way, i'm very new to linux generally.

**Comment by Senither** [comment]
Your message is `"Access denied for user 'root'@'localhost'"` which would indicate your database login information is either incorrect, or the account you're using doesn't have permissions to access the `"media"` table, seems more likely the database info is incorrect since you're using the `root` MySQL user which should have access to everything by default.

**Comment by teo0781** [comment]
Hello there, thank you for the fast response!
Yes, you were correct, i had an issue with my database setup, **as it was not listed in the install guide.**

I am now running into another problem, the error is
"[1049] Unknown database 'media'", again **this is also not in the install guide.**

By the way, since i'm commenting, may i ask, does this support subdomains? I don't really see the option for it anywhere.

**Comment by Senither** [comment]
You'd need to create the database yourself before you can actually use it, I guess I really should add that to the setup instructions too, however you can create the database by singing into the MySQL database and running `CREATE DATABASE media`, you can sign into the database by running `sudo mysql` on your machine, or by using `mysql -uroot -p` and then entering your account password.

In regards to the sub domain question, yes the media server supports multiple sub domains that you can setup and configure in the control panel, the only require is that all the sub domains actually points to the media server installation, you can find an example of what it looks like from my own version of the media server below.

![Media Server - Sub domains example](https://what-even-is.avairebot.com/i/ADisillusionedMotionlessLawyer)

The media server will pick a random URL when generating a new URL for you, including the URL defined the `.env` file, which means all the following links works and points to the same image:

    ⬇️ This is not in the list of URL domains in the screenshot, but is defined in the .env file, so it's included as an option when generating URLs.
    https://media.senither.com/i/ADisillusionedMotionlessLawyer

    ⬇️These are all in the URL list, and all point to the same image.
    https://what-even-is.avairebot.com/i/ADisillusionedMotionlessLawyer
    https://what-even-is.senither.com/i/ADisillusionedMotionlessLawyer
    https://avaire.is-just-a-me.me/i/ADisillusionedMotionlessLawyer
    https://senither.is-just-a-me.me/i/ADisillusionedMotionlessLawyer

**Comment by teo0781** [comment]
Status update!
I am past the database config! 

I am now kind of stuck on the "sudo apt-get install supervisor" step, the one after it, this is the error i get.

"teo@server:/etc/supervisor$ sudo supervisorctl start media-server-worker:*
media-server-worker: ERROR (no such group)"

Any possible solution?

**Comment by Senither** [comment]
Nice^^

Did you add the `media-server-worker.conf` file to the `/etc/supervisor/conf.d` directory? The file needs to exist there for Supervisor to be able to find the file, you also need to run the `sudo supervisorctl reread` and `sudo supervisorctl update` commands first so that Supervisor can find the file and knows what is in it.

Alternatively, you can set the `QUEUE_DRIVER` property in the `.env` file to `sync` instead, doing that will just skip the entire queue system and run all the tasks during the requests which can make the site slightly slower in some cases, especially when shorting URLs since normally a background task is added to the queue to take a screenshot of the original website which is then displayed on the control panel, and that can sometimes take a second or two, uploading images also generate thumbnails in different sizes which would add a bit more time to image upload requests, but that tends to go pretty quickly anyways.

It's easier to skip the queue system but it does make some parts of the site slightly slower since it can't run the code in the background and out of sight of the user, up to you what you'd like to do tho.

**Comment by teo0781** [comment]
I have skipped the queue system fully, set it to sync, i have done yarn install and yarn prod.

Now the problem is, **whenever i go to localhost, it's just the deafult apache2 page.**
I am sorry for wasting due to my lack of knowledge, but oh well, hopefully i'll learn linux better in the future.

**Comment by Senither** [comment]
If you're using Apache2 or a Ubuntu 20.04 LTS machine your site config should be located in `/etc/apache2/sites-available/000-default.conf`, the easiest solution is just to edit the file so that the `DocumentRoot` property point to your installation path instead of the default which should be `/var/www/html`.

After you have edited the config you can run `sudo apachectl configtest` to make sure the config will actually work, if you get an `Syntax OK` back from that you can restart apache to make the changes take effect using `systemctl restart apache2`.

**Comment by teo0781** [comment]
Yep, done that, now i'm running into another issue somehow???

Forbidden

You don't have permission to access this resource.
Apache/2.4.41 (Ubuntu) Server at localhost Port 80

**Comment by Senither** [comment]
That's most like an issue of the files not being accessible, the project should be located inside the `/var/www` directly somewhere in a subdirectory, and the messages should be `775`, you can try run the permission commands from the setup instructions on your installation:

    chmod -R 775 storage
    chmod -R 775 bootstrap/cache

    chown -R www-data:www-data storage
    chown -R www-data:www-data bootstrap/cache

If your project is currently not located inside the `/var/www` directory you can move all the files by using `mv your-installation-directory /var/www/media-server` which should move `your-installation-directory` to `/var/www/media-server`.

**Comment by teo0781** [comment]
This is, very strange, to say the least. Instead of an actual webpage, i just get a view of all the contents of the said media-server folder.

**Comment by Senither** [comment]
If you're seeing all the files listed on the web page then you need to change your Apache `DocumentRoot` again, it shouldn't be pointing to the installation directory directly, but the `public` folder inside of it, I guess that's my bad for not explaining it properly.

The system is built using [Laravel](https://laravel.com/) which is a PHP framework, and the entire framework is booted from the `index.php` file inside of the `public` directory, so the root of your website needs to point to that directory too.

**Comment by teo0781** [comment]
I have done that, now i get a blank page with the text "make(Kernel::class); $response = tap($kernel->handle( $request = Request::capture() ))->send(); $kernel->terminate($request, $response); "

**Comment by teo0781** [comment]
UPDATE: I have fixed the weird php code issue! 
I think i know how to fix the next issue, please give me a moment.

**Comment by Senither** [comment]
That would be the contents of the `index.php` file, you shouldn't see that if you have PHP installed and Apache is setup to use your PHP installation.

Try run `php -v` and make sure PHP is actually installed.

If PHP is installed on your machine then try run `sudo apt install libapache2-mod-php` to ensure that you have the Apache to PHP mod, so that Apache and PHP can talk with each other, you most likely need to restart apache after the mod is installed if it isn't installed already before it takes effect.

**Comment by teo0781** [comment]
Alright, next issue, again, apologies for bothering you this much. 

Once i go to localhost, it redirects me to localhost/login, thing is, it returns a 404 error.

**Comment by Senither** [comment]
It's all good^^

The 404 error represents the web server not being able to find the login file, which makes sense since it actually doesn't exists, [Laravel](https://laravel.com/) utilizes URL rewrites to create clean URLs, and handles the entire website from a single file, since your Apache installation seems to be a fresh install it might've not come with the rewrite module enabled, you can enable the mod using:

    a2enmod rewrite

After enabling the mod and restarting Apache it should work, if it doesn't do the trick you most likely have to allow overrides in the actually Apache configuration, you can find that at `/etc/apache2/apache2.conf`, and around line 150 - 170 you'll find something like this:

![Apache2 override config](https://alexis.is-just-a-me.me/i/ADidacticAbleTeam)

Just make sure the `AllowOverride` property is set to `All` for the `/var/www` directory.

> Apache needs to be restarted again before any changes you make to the `apache2.conf` file take effect.

**Comment by teo0781** [comment]
Woooo!!

It finnally works, even though the proccess for it was very long, would you mind if i remade the installation guide tomorrow?

**Comment by Senither** [comment]
Nice!

I'll add some notes to the wiki later today to help guide some of the questions people might have if they're new to hosting websites using Apache or Nginx, however, if you have anything else to add you're welcome to add stuff to the wiki too^^

Since the issue seems to have been resolved I'll close the issue for now.
