### ISSUE TITLE
Major wiki changes

### ISSUE THREAD

**Issue by teo0781** [Senither/ShareX-Media-Server#23]
I am unable to directly make a pull request to the wiki (github limitation), so to apply it you'll have to head over to my fork, and manually update it to this repo.

Things updated/added:
MySQL setup
MySQL prerequesite
Copying .env file (people often get confused)
Setting up the server with apache
... and more

And a whole another page: Additional configuration (Increase max upload size, more things in the future too?)

https://github.com/teo0781/ShareX-Media-Server

**Comment by Senither** [comment]
Thanks for the suggestions, however, I don't think everything really fits into the current wiki, especially since the following note is one of the first things you see in the installation guide.

> This guide does assume you are at least somewhat familiar with Linux systems, and already have everything defined in the prerequisites set up and ready.

MySQL isn't a prerequisite for the app either since you can choose to use SQLite which doesn't require you to install anything, or you can use any of the other [Laravel database drivers](https://laravel.com/docs/8.x/database#introduction), granted MySQL is recommended, but it is not required.

A guide for setting up both a LAMP and LEMP stacks was also recently added to the top of the installation guide which covers how to both set up Apache/Nginx, PHP, a MySQL server, setting up your first project, and how to install and enable mods, something that could be added is that you'd need the URL rewriting mod to fully set up the media server, so could add a note on how to do it for Apache and Nginx, as-well-as your note on how to raise the maximum upload size.

Thanks for the ideas and suggestions to the wiki, I'll add some more notes to the wiki later today or tomorrow 👍
