### ISSUE TITLE
[SUGGESTION] Gyazo-Like embeds

### ISSUE THREAD

**Issue by teo0781** [Senither/ShareX-Media-Server#27]
Hopefully you're not tired of me constantly suggesting more things.

-----

Anyways, the thing that i would want to be achieved with this suggestion would be a embed similar to this. https://cdn.teo0781.xyz/i/MtFf

You may ask, why though? 

1. It bypasses the upload limit, one of the main reasons people are switching to custom ShareX servers.
2. Instead of manually having to type in the "/preview" part after the file, this would do it automatically, if it can not, it simply would NOT embed.

-----

If i am correct, this should be very easy to implement, this would replace the current embed.
https://cdn.teo0781.xyz/i/HdpnsNEh

OR

The title would be the file name, description the current description, and the video/file the actual "image" in the embed, like shown in the 1st picture.

If it is not a video, or a file you can not easily embed, then it would deafult back to the current one.

-----

Hopefully i am not asking for too much.

**Comment by Senither** [comment]
It's not as easy as you might think since multiple different file types are supported by the previewer feature, and depending on the type that should be previewed in the embed different meta tags also need to be generated in order to support them being rendered correctly, doing it just for images would be easy enough, but doing it for other file types makes it more complicated since the media server would need to generate image previews of the files to add to the meta tags too.

Regarding your 2nd point, you shouldn't have to type in the `/preview` part of the URL manually if you're copying the URL straight from the media server since it comes with it already.

**Comment by teo0781** [comment]
> It's not as easy as you might think since multiple different file types are supported by the previewer feature, and depending on the type that should be previewed in the embed different meta tags also need to be generated in order to support them being rendered correctly, doing it just for images would be easy enough, but doing it for other file types makes it more complicated since the media server would need to generate image previews of the files to add to the meta tags too.
> 
> Regarding your 2nd point, you shouldn't have to type in the `/preview` part of the URL manually if you're copying the URL straight from the media server since it comes with it already.

Well for your first point, i personally think just images and videos should be more then enough. So .mov, .mp4, etc. And for the images you already know the formats.

Your 2nd response is i meant to make it embed into discord, without having to make people go to the link, which is currently required.

About the image previews, couldn't you use the code the url shortener uses but modified?

**Comment by Senither** [comment]
The URL previews uses [Browsershot](https://github.com/spatie/browsershot) to take a screenshot of the entire webpage and save it as an image, using the same thing for videos would include in lot of blank unused space inside the thumbnails which would make the actual content look tiny depending on the file dimensions, it would be a lot better to use something like [FFmpeg](https://roundup.ffmpeg.org/) which can extract frames from the video itself as images, however, I'm not super keen on adding another big library requirement for the project just so video image file uploads has a nicer preview.

> Well for your first point, i personally think just images and videos should be more then enough. So .mov, .mp4, etc. And for the images you already know the formats.
>
> Your 2nd response is i meant to make it embed into discord, without having to make people go to the link, which is currently required.

I don't get the idea that file uploads really need to support images, there is an entire separate category for just images that works just fine, posting image links into Discord also creates the embed preview just fine, I'm aware videos don't work just yet but I'm assuming that's either something to do with the headers the previewer is responding with, or with how the video is returned from the previewer, either way it's something I'm looking into and should be fixed at some point so that works too.

**Comment by teo0781** [comment]
>or with how the video is returned from the previewer, either way it's something I'm looking into and should be fixed at some point so that works too.

Ah okay, didn't know you knew about the issue, if you're already going to fix the headers for it, wouldn't it make sense to get rid of the upload limit while at it (by creating a custom embed that uses the headers)?

Again, not trying to be rude, just a suggestion.

**Comment by Senither** [comment]
What upload limit are you referring to? The only sorta limit when uploading files is the rate limit, and that only limits you to uploading 60 files per minute.

**Comment by teo0781** [comment]
> 
> 
> What upload limit are you referring to? The only sorta limit when uploading files is the rate limit, and that only limits you to uploading 60 files per minute, any other limit would be something created by your PHP or server configuration, not the app itself.

The embed limit, if i remember so correctly, if it is larger then 8 mb, it will not embed. 

This was on another uploader server, so i may be wronb.

**Comment by Senither** [comment]
I'm super confused now, if the Discord embed limit, which I assume is what you're referring to, has an upload limit of 8 MB, anything I change on the media server side wouldn't affect that at all, also Discords embed previews of files shouldn't be limited to 8 MB since the files aren't being hosted directly in Discord anyways, similarly to how 10 hours videos on YouTube can be embed into Discord just fine.

**Comment by teo0781** [comment]
> 
> 
> I'm super confused now, if the Discord embed limit, which I assume is what you're referring to, has an upload limit of 8 MB, anything I change on the media server side wouldn't affect that at all, also Discords embed previews of files shouldn't be limited to 8 MB since the files aren't being hosted directly in Discord anyways, similarly to how 10 hours videos on YouTube can be embed into Discord just fine.

Let me further explain this.

**Comment by Senither** [comment]
I'm back from work now so got some time.

> Gyazo did, somehow, it can embed files larger than 8 mb.

I was referring to the if Discord didn't want to create an embed around images larger than 8 MB, then changing anything on the media server-side wouldn't affect it at all, it had nothing at all to do with anything Gyazo did or currently do.

Regarding the links to the embed suggestions, they're both oEmbed solutions that don't actually work for this issue, the solution would be to use meta tags that would allow Discord to create an embed around the content on the web page, creating an oEmbed just creates another API endpoint, but there would be nothing to consume it.

This is also getting off-topic and it really doesn't feel like we're getting anywhere, so if you have any suggestions or ideas regarding the embeds you can contact me on Discord instead at `Senither#0001`, should be a lot easier and quicker to talk there, that way we're also not spamming people who watch the project with notifications.
