### ISSUE TITLE
New user unable to login

### ISSUE THREAD

**Issue by LouisHacking** [Senither/ShareX-Media-Server#9]
Made a new user and they're unable to login on their computer...

I can use their credentials and it works fine. Using same credentials on their machine results in the following...
I've tried clearing all cache, redone composer install and yarn

<img width="473" alt="Screenshot 2021-03-04 at 21 02 20" src="https://user-images.githubusercontent.com/9805436/110029994-11c42680-7d2d-11eb-9534-1d64768a594a.png">

**Comment by Senither** [comment]
That's a pretty low res image, however from what I can read in the image it looks like you're getting a file lock error, this is most likely caused by the permissions set to the `storage/framework/cache` directory, make sure that the application has full read and write access to everything in the storage directory, as the app regularly reads and writes to that folder.

You can ensure the app always has permissions to the storage folder by recursively setting the permissions in the directory to 775, and changing the ownership of the directory and its files to the `www-data` user group on Linux machines.
You can try using the commands below from the root of your installation.
```bash
sudo chmod -R 775 storage/
sudo chown -R www-data:www-data storage/

**Comment by LouisHacking** [comment]
Thanks. I'll get him to try again, I had it set to www-data and 777 but perhaps that's too high?

**Comment by Senither** [comment]
Setting the permissions to 777 would work too, it is a bit safer to set the permissions to 775 since that doesn't give everyone access to everything inside of the storage folder, however, all that's stored in the directory is some caches, logs, and the uploaded images so you might still be fine using 777.

**Comment by LouisHacking** [comment]
I'm guessing it's an issue his side, it works on his other computer...
